server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.0.1
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0